markdown: redcarpet
permalink: /posts/:title

gems:
  - jekyll-sitemap

name: Scott Bigelow
url: http://www.scottbigelow.com
description: DevOps, Site Reliability, and other random Linux-based musings
twitter: epheph
